# Generated by Django 4.1.11 on 2023-11-05 13:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('category', '0001_initial'),
        ('subcategory', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maker', models.CharField(max_length=50)),
                ('built_in', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('stars', models.IntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('orderId', models.ManyToManyField(blank=True, null=True, to='orders.order')),
                ('seller_id', models.ManyToManyField(blank=True, null=True, to='seller.seller')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcategory.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 11, 5, 13, 55, 22, 269931))),
                ('prod_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
