# Generated by Django 4.1.11 on 2023-10-05 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('subcategory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('maker', models.CharField(max_length=50)),
                ('built_in', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(storage=djongo.storage.GridFSStorage(base_url='myfiles/', collection='myfiles'), upload_to='products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcategory.subcategory')),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
