# Generated by Django 4.1.11 on 2023-10-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('products', '0003_alter_product_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_id',
            field=models.ManyToManyField(to='seller.seller'),
        ),
    ]
