# Generated by Django 4.1.11 on 2023-11-06 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productchart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productchart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 7, 4, 0, 228243)),
        ),
    ]
