# Generated by Django 4.1.11 on 2023-11-06 07:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productchart_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productchart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 7, 35, 12, 57121, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productchart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productchart',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
