# Generated by Django 4.1.11 on 2023-11-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productchart_date_alter_productchart_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productchart',
            name='date',
            field=models.DateField(),
        ),
    ]
